# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new internal version to the Google Play"
  lane :internal do
    # Return the number of commits in current git branch
    build_number = number_of_commits()
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "appbundle", "--build-number=#{build_number}", "--target-platform", "android-arm,android-arm64")
    end
    changelog_from_git_commits
    upload_to_play_store(track: 'internal', aab: '../build/app/outputs/bundle/release/app.aab')
  end
end
